'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.296
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CST.CBT.eIPSTA.PracticeStudent_Trial.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  echo off
        '''rem for %%V in ( %temp%\Student\*.msi ) do %%V
        '''if exist %temp%\Student_VetNorse_demo\setup.exe %temp%\Student_VetNorse_demo\setup.exe
        '''del %1
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property __() As String
            Get
                Return ResourceManager.GetString("__", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DocumentElement&gt;
        '''  &lt;CATEGORY&gt;
        '''    &lt;CATEGORYID&gt;10&lt;/CATEGORYID&gt;
        '''    &lt;CATEGORYNAME&gt;国語&lt;/CATEGORYNAME&gt;
        '''    &lt;PARENTCATEGORYID /&gt;
        '''    &lt;DISPLAYID&gt;01&lt;/DISPLAYID&gt;
        '''    &lt;CATEGORYCLASS&gt;1&lt;/CATEGORYCLASS&gt;
        '''    &lt;KEYWORD /&gt;
        '''    &lt;LEVELQUESTIONCOUNT1&gt;17&lt;/LEVELQUESTIONCOUNT1&gt;
        '''    &lt;LEVELQUESTIONCOUNT2&gt;13&lt;/LEVELQUESTIONCOUNT2&gt;
        '''    &lt;LEVELQUESTIONCOUNT3&gt;10&lt;/LEVELQUESTIONCOUNT3&gt;
        '''    &lt;CREATE_DATE&gt;1900/01/01&lt;/CREATE_DATE&gt;
        '''    &lt;UPDATE_DATE&gt;2012/12/27 13:17:10&lt;/UPDATE_DATE&gt;
        '''    &lt;SYNT [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Category() As String
            Get
                Return ResourceManager.GetString("Category", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property CBT() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CBT", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DocumentElement&gt;
        '''  &lt;Group&gt;
        '''    &lt;GROUPCODE&gt;VETNurse&lt;/GROUPCODE&gt;
        '''    &lt;GROUPNAME&gt;動物看護師認定試験&lt;/GROUPNAME&gt;
        '''    &lt;APPLICANT /&gt;
        '''    &lt;COURSE /&gt;
        '''    &lt;STUDENTCOUNT /&gt;
        '''    &lt;TESTSTART /&gt;
        '''    &lt;TESTEND /&gt;
        '''    &lt;GROUPMANAGERID&gt;d&lt;/GROUPMANAGERID&gt;
        '''    &lt;GROUPMANAGERNAME /&gt;
        '''    &lt;PASSWORD&gt;d&lt;/PASSWORD&gt;
        '''    &lt;STATE /&gt;
        '''    &lt;FIRSTSTSRTDAY /&gt;
        '''    &lt;FIRSTENDDAY /&gt;
        '''    &lt;SECONDSTSRTDAY /&gt;
        '''    &lt;SECONDENDDAY /&gt;
        '''    &lt;COURSENO /&gt;
        '''    &lt;CREATE_DATE /&gt;
        '''    &lt;UPDATE_DATE /&gt;
        '''  &lt;/Group&gt;
        '''&lt;/D [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GroupVETNurse() As String
            Get
                Return ResourceManager.GetString("GroupVETNurse", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Help01() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Help01", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DocumentElement&gt;
        '''  &lt;PracticeQuestionList&gt;
        '''    &lt;QUESTIONCODE&gt;P0000001&lt;/QUESTIONCODE&gt;
        '''    &lt;QUESTIONCLASS&gt;1&lt;/QUESTIONCLASS&gt;
        '''    &lt;MAINCODE /&gt;
        '''    &lt;MIDDLEQUESTIONINDEX /&gt;
        '''    &lt;THEME&gt;国語&lt;/THEME&gt;
        '''    &lt;LEVEL /&gt;
        '''    &lt;CATEGORYID&gt;0101&lt;/CATEGORYID&gt;
        '''    &lt;FORMAT /&gt;
        '''    &lt;CORRECTANSWER&gt;４&lt;/CORRECTANSWER&gt;
        '''    &lt;STATE&gt;0&lt;/STATE&gt;
        '''    &lt;QUESTIONTYPE&gt;0&lt;/QUESTIONTYPE&gt;
        '''    &lt;CREATE_DATE&gt;2013/01/18 15:10:49&lt;/CREATE_DATE&gt;
        '''    &lt;UPDATE_DATE&gt;2013/01/18 15:10:49&lt;/UPDATE_DATE&gt;
        '''  &lt;/Practi [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PracticeQuestionList() As String
            Get
                Return ResourceManager.GetString("PracticeQuestionList", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000001() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000001", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000002() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000002", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000003() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000003", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000004() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000004", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000005() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000005", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000006() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000006", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000007() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000007", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000008() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000008", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000009() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000009", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000010() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000010", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000011() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000011", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000012() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000012", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000013() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000013", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000014() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000014", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000015() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000015", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000016() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000016", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000017() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000017", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000018() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000018", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000019() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000019", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property PracticeQuestionP0000020() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PracticeQuestionP0000020", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Result() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Result", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property setup() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("setup", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SpreadSheetSpecification() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpreadSheetSpecification", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DocumentElement xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        '''	&lt;Student&gt;
        '''		&lt;USERID&gt;999999&lt;/USERID&gt;
        '''		&lt;NAME&gt;体験版&lt;/NAME&gt;
        '''		&lt;SECTION1 /&gt;
        '''		&lt;SECTION2 /&gt;
        '''		&lt;PASSWORD&gt;999999&lt;/PASSWORD&gt;
        '''		&lt;NOTE /&gt;
        '''		&lt;TESTCOUNT&gt;0&lt;/TESTCOUNT&gt;
        '''		&lt;UPLOADDATE&gt;2012/12/17 08:19:17&lt;/UPLOADDATE&gt;
        '''		&lt;STUDENTSSTART /&gt;
        '''		&lt;STUDENTSEND /&gt;
        '''		&lt;CREATE_DATE&gt;2012/11/14 15:33:42&lt;/CREATE_DATE&gt;
        '''		&lt;UPDATE_DATE&gt;2012/11/14 15:33:42&lt;/UPDATE_DATE&gt;
        '''	&lt;/Student&gt;
        '''	&lt;Student&gt;
        '''		&lt;USER [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StudentVETNurse() As String
            Get
                Return ResourceManager.GetString("StudentVETNurse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DocumentElement&gt;
        '''  &lt;SynthesisDetail&gt;
        '''    &lt;TESTNO&gt;1&lt;/TESTNO&gt;
        '''    &lt;QUESTIONCODE&gt;P0000001&lt;/QUESTIONCODE&gt;
        '''    &lt;SHOWNO&gt;1&lt;/SHOWNO&gt;
        '''    &lt;CREATE_DATE&gt;2013/01/18 15:11:31&lt;/CREATE_DATE&gt;
        '''    &lt;UPDATE_DATE&gt;2013/01/18 15:11:31&lt;/UPDATE_DATE&gt;
        '''  &lt;/SynthesisDetail&gt;
        '''  &lt;SynthesisDetail&gt;
        '''    &lt;TESTNO&gt;1&lt;/TESTNO&gt;
        '''    &lt;QUESTIONCODE&gt;P0000002&lt;/QUESTIONCODE&gt;
        '''    &lt;SHOWNO&gt;2&lt;/SHOWNO&gt;
        '''    &lt;CREATE_DATE&gt;2013/01/18 15:11:31&lt;/CREATE_DATE&gt;
        '''    &lt;UPDATE_DATE&gt;2013/01/18 15:11:31&lt;/UPDATE_DATE&gt;        ''' [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SynthesisDetail30VETNurse() As String
            Get
                Return ResourceManager.GetString("SynthesisDetail30VETNurse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DocumentElement&gt;
        '''  &lt;SynthesisHeader&gt;
        '''    &lt;TESTNO&gt;1&lt;/TESTNO&gt;
        '''    &lt;TESTNAME&gt;体験版&lt;/TESTNAME&gt;
        '''    &lt;CREATE_DATE&gt;2013/01/18 15:11:31&lt;/CREATE_DATE&gt;
        '''    &lt;UPDATE_DATE&gt;2013/01/18 15:11:31&lt;/UPDATE_DATE&gt;
        '''  &lt;/SynthesisHeader&gt;
        '''&lt;/DocumentElement&gt; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SynthesisHeader30VETNurse() As String
            Get
                Return ResourceManager.GetString("SynthesisHeader30VETNurse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DocumentElement&gt;
        '''  &lt;TESTNAME&gt;
        '''    &lt;NAME&gt;動物看護師コンピュータ試験（CBT）体験試験&lt;/NAME&gt;
        '''  &lt;/TESTNAME&gt;
        '''&lt;/DocumentElement&gt; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TestName() As String
            Get
                Return ResourceManager.GetString("TestName", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
