'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.296
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CST.CBT.eIPSTA.PracticeStudent_Trial.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DocumentElement&gt;
        '''  &lt;Group&gt;
        '''    &lt;GROUPCODE&gt;VETNurse&lt;/GROUPCODE&gt;
        '''    &lt;GROUPNAME&gt;CBTデモ&lt;/GROUPNAME&gt;
        '''    &lt;APPLICANT /&gt;
        '''    &lt;COURSE /&gt;
        '''    &lt;STUDENTCOUNT /&gt;
        '''    &lt;TESTSTART /&gt;
        '''    &lt;TESTEND /&gt;
        '''    &lt;GROUPMANAGERID&gt;d&lt;/GROUPMANAGERID&gt;
        '''    &lt;GROUPMANAGERNAME /&gt;
        '''    &lt;PASSWORD&gt;d&lt;/PASSWORD&gt;
        '''    &lt;STATE /&gt;
        '''    &lt;FIRSTSTSRTDAY /&gt;
        '''    &lt;FIRSTENDDAY /&gt;
        '''    &lt;SECONDSTSRTDAY /&gt;
        '''    &lt;SECONDENDDAY /&gt;
        '''    &lt;COURSENO /&gt;
        '''    &lt;CREATE_DATE /&gt;
        '''    &lt;UPDATE_DATE /&gt;
        '''  &lt;/Group&gt;
        '''&lt;/Docum [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Group() As String
            Get
                Return ResourceManager.GetString("Group", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Help01() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Help01", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DocumentElement xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        '''	&lt;Student&gt;
        '''		&lt;USERID&gt;CST001&lt;/USERID&gt;
        '''		&lt;NAME&gt;ＣＳ 太郎&lt;/NAME&gt;
        '''		&lt;SECTION1 /&gt;
        '''		&lt;SECTION2 /&gt;
        '''		&lt;PASSWORD&gt;cst001&lt;/PASSWORD&gt;
        '''		&lt;NOTE /&gt;
        '''		&lt;TESTCOUNT&gt;0&lt;/TESTCOUNT&gt;
        '''		&lt;UPLOADDATE&gt;2012/12/17 08:19:17&lt;/UPLOADDATE&gt;
        '''		&lt;STUDENTSSTART /&gt;
        '''		&lt;STUDENTSEND /&gt;
        '''		&lt;CREATE_DATE&gt;2012/11/14 15:33:42&lt;/CREATE_DATE&gt;
        '''		&lt;UPDATE_DATE&gt;2012/11/14 15:33:42&lt;/UPDATE_DATE&gt;
        '''	&lt;/Student&gt;
        '''	&lt;Student&gt;
        '''		&lt;US [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Student() As String
            Get
                Return ResourceManager.GetString("Student", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DocumentElement&gt;
        '''  &lt;TESTNAME&gt;
        '''    &lt;NAME&gt;デモ試験NO1&lt;/NAME&gt;
        '''  &lt;/TESTNAME&gt;
        '''&lt;/DocumentElement&gt; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TestName() As String
            Get
                Return ResourceManager.GetString("TestName", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
