'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.296
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CST.CBT.eIPSTA.Common.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;CATEGORY&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;CATEGORY&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;CATEGORY&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;CATEGORY&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name=&quot;CATEGORYID&quot; type=&quot;x [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Category() As String
            Get
                Return ResourceManager.GetString("Category", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DocumentElement&gt;
        '''  &lt;CATEGORY&gt;
        '''    &lt;CATEGORYID&gt;2&lt;/CATEGORYID&gt;
        '''    &lt;CATEGORYNAME&gt;基礎動物看護学Ⅰ&lt;/CATEGORYNAME&gt;
        '''    &lt;PARENTCATEGORYID /&gt;
        '''    &lt;DISPLAYID&gt;01&lt;/DISPLAYID&gt;
        '''    &lt;CATEGORYCLASS&gt;1&lt;/CATEGORYCLASS&gt;
        '''    &lt;KEYWORD /&gt;
        '''    &lt;LEVELQUESTIONCOUNT1&gt;17&lt;/LEVELQUESTIONCOUNT1&gt;
        '''    &lt;LEVELQUESTIONCOUNT2&gt;13&lt;/LEVELQUESTIONCOUNT2&gt;
        '''    &lt;LEVELQUESTIONCOUNT3&gt;10&lt;/LEVELQUESTIONCOUNT3&gt;
        '''    &lt;CREATE_DATE&gt;1900/01/01&lt;/CREATE_DATE&gt;
        '''    &lt;UPDATE_DATE&gt;2012/12/27 13:17:10&lt;/UPDATE_DATE&gt;
        '''     [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CategoryData() As String
            Get
                Return ResourceManager.GetString("CategoryData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;Collection&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;Collection&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Collection&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;Collection&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name=&quot;COURSENO&quot; t [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Collection() As String
            Get
                Return ResourceManager.GetString("Collection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;Course&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;Course&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Course&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;Course&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name=&quot;COURSENO&quot; type=&quot;xs:string&quot;  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Course() As String
            Get
                Return ResourceManager.GetString("Course", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;Decryptionkey&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;Decryptionkey&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Decryptionkey&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;Decryptionkey&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name= [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Decryptionkey() As String
            Get
                Return ResourceManager.GetString("Decryptionkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;Delivery&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;Delivery&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Delivery&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;Delivery&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name=&quot;STATE&quot; type=&quot;xs:str [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Delivery() As String
            Get
                Return ResourceManager.GetString("Delivery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;Group&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;Group&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Group&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;Group&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name=&quot;GROUPCODE&quot; type=&quot;xs:string&quot; min [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Group() As String
            Get
                Return ResourceManager.GetString("Group", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;DocumentElement&gt;
        '''  &lt;MENU&gt;
        '''    &lt;INDEX&gt;1&lt;/INDEX&gt;
        '''    &lt;MENUMODE&gt;0&lt;/MENUMODE&gt;
        '''    &lt;ID&gt;100000&lt;/ID&gt;
        '''    &lt;NAME&gt;メインメニュー&lt;/NAME&gt;
        '''    &lt;CAPTION /&gt;
        '''    &lt;NAME_SPACE /&gt;
        '''    &lt;FORMNAME /&gt;
        '''    &lt;PARENTID /&gt;
        '''  &lt;/MENU&gt;
        '''  &lt;MENU&gt;
        '''    &lt;INDEX&gt;2&lt;/INDEX&gt;
        '''    &lt;MENUMODE&gt;0&lt;/MENUMODE&gt;
        '''    &lt;ID&gt;110000&lt;/ID&gt;
        '''    &lt;NAME&gt;問題管理&lt;/NAME&gt;
        '''    &lt;CAPTION&gt;問題のＷＯＲＤ取込、確認&lt;/CAPTION&gt;
        '''    &lt;NAME_SPACE /&gt;
        '''    &lt;FORMNAME /&gt;
        '''    &lt;PARENTID&gt;100000&lt;/PARENTID&gt;
        '''  &lt;/MENU&gt;
        '''  &lt;MENU&gt;
        '''    &lt;INDEX&gt;3 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Menu() As String
            Get
                Return ResourceManager.GetString("Menu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;MENU&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;MENU&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;MENU&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;MENU&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name=&quot;INDEX&quot; type=&quot;xs:string&quot; minOccurs=&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MenuSchema() As String
            Get
                Return ResourceManager.GetString("MenuSchema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;DocumentElement&gt;
        '''  &lt;Message&gt;
        '''    &lt;Id&gt;E001&lt;/Id&gt;
        '''    &lt;Value&gt;ユーザIDまたはパスワードが正しくありません。&lt;/Value&gt;
        '''  &lt;/Message&gt;
        '''  &lt;Message&gt;
        '''    &lt;Id&gt;E002&lt;/Id&gt;
        '''    &lt;Value&gt;ユーザIDが入力されていません。&lt;/Value&gt;
        '''  &lt;/Message&gt;
        '''  &lt;Message&gt;
        '''    &lt;Id&gt;E003&lt;/Id&gt;
        '''    &lt;Value&gt;パスワードが入力されていません。&lt;/Value&gt;
        '''  &lt;/Message&gt;
        '''  &lt;Message&gt;
        '''    &lt;Id&gt;E004&lt;/Id&gt;
        '''    &lt;Value&gt;認証できません。システム管理者に連絡してください。&lt;/Value&gt;
        '''  &lt;/Message&gt;
        '''  &lt;Message&gt;
        '''    &lt;Id&gt;E005&lt;/Id&gt;
        '''    &lt;Value&gt;{0}が入力されていません。&lt;/Value&gt;
        '''  &lt;/Message&gt;
        '''  &lt;Message&gt;
        '''  &lt;Id&gt;E006 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property message() As String
            Get
                Return ResourceManager.GetString("message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;MiniResultDetail&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;MiniResultDetail&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;MiniResultDetail&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;MiniResultDetail&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element name=&quot;USERID&quot; type=&quot;x [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MiniResultDetail() As String
            Get
                Return ResourceManager.GetString("MiniResultDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;MiniResultHeader&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;MiniResultHeader&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;MiniResultHeader&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;MiniResultHeader&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element name=&quot;USERID&quot; type=&quot;x [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MiniResultHeader() As String
            Get
                Return ResourceManager.GetString("MiniResultHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;PracticeQuestionList&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;PracticeQuestionList&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;PracticeQuestionList&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;PracticeQuestionList&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''    [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PracticeQuestionList() As String
            Get
                Return ResourceManager.GetString("PracticeQuestionList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;QuestionList&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;QuestionList&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;QuestionList&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;QuestionList&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name=&quot;TES [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property QuestionList() As String
            Get
                Return ResourceManager.GetString("QuestionList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;Review&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;Review&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Review&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;Review&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element name=&quot;QUESTIONCODE&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot; /&gt;
        '''						 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Review() As String
            Get
                Return ResourceManager.GetString("Review", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;SerialResultDetail&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;SerialResultDetail&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;SerialResultDetail&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;SerialResultDetail&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element name=&quot;USERID&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SerialResultDetail() As String
            Get
                Return ResourceManager.GetString("SerialResultDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;SerialResultHeader&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;SerialResultHeader&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;SerialResultHeader&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;SerialResultHeader&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element name=&quot;USERID&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SerialResultHeader() As String
            Get
                Return ResourceManager.GetString("SerialResultHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;SpecificDetail&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;SpecificDetail&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;SpecificDetail&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;SpecificDetail&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element name=&quot;TESTNO&quot; type=&quot;xs:string [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SpecificDetail() As String
            Get
                Return ResourceManager.GetString("SpecificDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;SpecificHeader&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;SpecificHeader&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;SpecificHeader&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;SpecificHeader&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element name=&quot;TESTNO&quot; type=&quot;xs:string [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SpecificHeader() As String
            Get
                Return ResourceManager.GetString("SpecificHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;Student&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;Student&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Student&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;Student&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name=&quot;USERID&quot; type=&quot;xs:string [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Student() As String
            Get
                Return ResourceManager.GetString("Student", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;SynthesisDetail&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;SynthesisDetail&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;SynthesisDetail&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;SynthesisDetail&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element name=&quot;TESTNO&quot; type=&quot;xs:st [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SynthesisDetail() As String
            Get
                Return ResourceManager.GetString("SynthesisDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;SynthesisHeader&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;SynthesisHeader&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;SynthesisHeader&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;SynthesisHeader&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element name=&quot;TESTNO&quot; type=&quot;xs:st [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SynthesisHeader() As String
            Get
                Return ResourceManager.GetString("SynthesisHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;SynthesisHeader&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;SynthesisHeader&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;SynthesisHeader&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;SynthesisHeader&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element name=&quot;TESTNO&quot; type=&quot;xs:st [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SynthesisHeader1() As String
            Get
                Return ResourceManager.GetString("SynthesisHeader1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;SynthesisResultDetail&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;SynthesisResultDetail&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;SynthesisResultDetail&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;SynthesisResultDetail&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element n [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SynthesisResultDetail() As String
            Get
                Return ResourceManager.GetString("SynthesisResultDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;SynthesisResultDetail&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;SynthesisResultDetail&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;SynthesisResultDetail&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;SynthesisResultDetail&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element n [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SynthesisResultDetail1() As String
            Get
                Return ResourceManager.GetString("SynthesisResultDetail1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;SynthesisResultHeader&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;SynthesisResultHeader&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;SynthesisResultHeader&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;SynthesisResultHeader&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element n [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SynthesisResultHeader() As String
            Get
                Return ResourceManager.GetString("SynthesisResultHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;SynthesisResultHeader&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''	&lt;xs:element name=&quot;SynthesisResultHeader&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;SynthesisResultHeader&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''				&lt;xs:element name=&quot;SynthesisResultHeader&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element n [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SynthesisResultHeader1() As String
            Get
                Return ResourceManager.GetString("SynthesisResultHeader1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;SystemUser&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;SystemUser&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;SystemUser&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;SystemUser&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name=&quot;USER&quot; type= [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SystemUser() As String
            Get
                Return ResourceManager.GetString("SystemUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;TESTNAME&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;TESTNAME&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;TESTNAME&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;TESTNAME&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name=&quot;NAME&quot; type=&quot;xs:stri [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TestName() As String
            Get
                Return ResourceManager.GetString("TestName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;TestResultDeail&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;TestResultDeail&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;TestResultDeail&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;TestResultDeail&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:eleme [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TestResultDetail() As String
            Get
                Return ResourceManager.GetString("TestResultDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;TestResultHeader&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;TestResultHeader&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;TestResultHeader&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;TestResultHeader&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:e [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TestResultHeader() As String
            Get
                Return ResourceManager.GetString("TestResultHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;WEBSERVICEURL&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;WEBSERVICEURL&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;WEBSERVICEURL&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;WEBSERVICEURL&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name= [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property WebServiceUrl() As String
            Get
                Return ResourceManager.GetString("WebServiceUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;xs:schema id=&quot;WEBSERVICEURL&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''  &lt;xs:element name=&quot;WEBSERVICEURL&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;WEBSERVICEURL&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''        &lt;xs:element name=&quot;WEBSERVICEURL&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name= [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property WebServiceUrl1() As String
            Get
                Return ResourceManager.GetString("WebServiceUrl1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
