'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.269
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CST.CBT.eIPSTA.GroupManager.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Print() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Print", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property QuestionReport() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("QuestionReport", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property RandomTestResultListDetailReport() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RandomTestResultListDetailReport", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property RandomTestResultListReport() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RandomTestResultListReport", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property RandomTestStudentResultListReport() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RandomTestStudentResultListReport", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property ResultList() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ResultList", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property ScoreAnalysis() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ScoreAnalysis", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SerialPracticeCategoryAnalysisReport() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SerialPracticeCategoryAnalysisReport", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SerialPracticeQuestionAnalysisReport() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SerialPracticeQuestionAnalysisReport", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SerialPracticeResultDetailReport() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SerialPracticeResultDetailReport", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SerialPracticeResultReport() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SerialPracticeResultReport", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SpecificErrataList10() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpecificErrataList10", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SpecificErrataList20() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpecificErrataList20", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SpecificErrataList30() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpecificErrataList30", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SpecificErrataList40() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpecificErrataList40", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SpecificQuestionAnalysisReport() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpecificQuestionAnalysisReport", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SpecificResultListReport() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpecificResultListReport", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SynthesisErrataList() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SynthesisErrataList", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SynthesisQuestionAnalysisReport() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SynthesisQuestionAnalysisReport", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SynthesisResultReport() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SynthesisResultReport", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
